# Autogenerated with DRAKON Editor 1.27

def state machine(standalone):
    while True:
        #item 510001
        if receive == receive==tb:
            while True:
                #item 600001
                if receive == A:
                    break
                else:
                    pass
                #item 600002
                if receive == B:
                    pass
                else:
                    #item 600003
                    if receive == C:
                        pass
                    else:
                        #item 600004
                        raise Exception("Not expected:  " + str(receive))
                    break
            break
        else:
            pass
        #item 510002
        if receive == udtl:
            pass
        else:
            #item 510003
            if receive == udtl_header:
                pass
            else:
                #item 510004
                raise Exception("Not expected:  " + str(receive))
            break


