/* Autogenerated with DRAKON Editor 1.27 */
#ifndef STATE_MACHINE_H79098
#define STATE_MACHINE_H79098



int make_state_machine(void);
int state_machine_A(int* machine);
int state_machine_B(int* machine);
int state_machine_C(int* machine);
int state_machine_receive==tb(int* machine);
int state_machine_udtl(int* machine);
int state_machine_udtl_header(int* machine);





#endif

